name: Try to upload

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.6.24/cr'
        name: 'cr'
        version: '0.6.24'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.6.24/caps'
        name: 'caps'
        version: '0.6.24'

    - run: caps --ci && yarn && yarn compile-server && yarn compile-page && yarn release-page && yarn release-server

    - run: mkdir -p dist-server && mv dist/server.js dist-server && cp package.json dist-server/
      name: Copy server scripts

    - name: Upload web assets
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"

    - name: Upload server script
      id: deploy-server
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist-server/*'
        dest: 'rsync-user@tiye.me:/servers/paste-sharing/'

    - name: Display status from deploy
      run: echo "${{ steps.deploy-server.outputs.status }}"
